-- Agenda da solicitud (matching por disponibilidade + urgência).
-- Rodar no SQL Editor depois do schema oficial.

CREATE TABLE IF NOT EXISTS public.service_schedule (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  request_id text,
  schedule_type text NOT NULL,
  urgency_level text,
  start_date date,
  end_date date,
  start_time time,
  end_time time,
  flexible_time boolean DEFAULT false,
  immediate_available boolean,
  timezone text,
  period text,
  summary text
);

CREATE TABLE IF NOT EXISTS public.service_schedule_days (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id bigint REFERENCES public.service_schedule(id) ON DELETE CASCADE,
  date date NOT NULL,
  period text,
  start_time time,
  end_time time
);

ALTER TABLE public.service_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_schedule_days ENABLE ROW LEVEL SECURITY;
